package go2openapi

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

func getFunctionName(i interface{}) string {
	return runtime.FuncForPC(reflect.ValueOf(i).Pointer()).Name()
}

// resolveSourceFile resolves the source file for a handler when SourceFileName
// is "<autogenerated>" (common with newer Go toolchains for method value wrappers).
// It extracts the package path from MainHandlerName, converts it to a local directory,
// and finds the .go file containing the method.
func resolveSourceFile(mainHandlerName string, goModName string, methodName string) string {
	// mainHandlerName looks like:
	//   github.com/livesession/go2openapi/test/app.(*api).testBaseControllerRequestStructTEST-fm
	// Extract package path: everything before the last segment after splitting by "/"
	// then trim from the first "." that's part of the type/method (not the package path dots)

	name := strings.TrimSuffix(mainHandlerName, compilerClousureSuffix)

	// Find the package path by finding where the type/func name starts
	// The package path ends at the last "/" segment's first "."
	lastSlash := strings.LastIndex(name, "/")
	if lastSlash == -1 {
		return ""
	}
	dotAfterLastSlash := strings.Index(name[lastSlash:], ".")
	if dotAfterLastSlash == -1 {
		return ""
	}
	pkgPath := name[:lastSlash+dotAfterLastSlash] // github.com/livesession/go2openapi/test/app

	// Strip the module name to get the relative directory
	relDir := strings.TrimPrefix(pkgPath, goModName)
	relDir = strings.TrimPrefix(relDir, "/")
	if relDir == "" {
		relDir = "."
	}

	// Check go.mod replace directives
	if replacement, ok := goModReplace[pkgPath]; ok {
		relDir = replacement
	}

	// Find the .go file in that directory containing the method
	entries, err := os.ReadDir(relDir)
	if err != nil {
		return ""
	}

	fset := token.NewFileSet()
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		filePath := filepath.Join(relDir, entry.Name())
		f, err := parser.ParseFile(fset, filePath, nil, 0)
		if err != nil {
			continue
		}
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			if fn.Name.Name == methodName {
				return "./" + filePath
			}
		}
	}

	return ""
}

// TODO: reject middlewares - only last method from router
// TODO: support multiple method declarations in different files
func irisRouterStrategy(options *Options, openapi *openapi3.T) error {
	app, searchIdentifiers, structsMappingRootPath, goModName, ignoreRoutes, require :=
		options.iris, options.SearchIdentifiers, options.StructsMappingRootPath, options.GoModName, options.IgnoreRoutes, options.Require

	structsMapping, err := mapStructsFromFiles(options.GoModName, structsMappingRootPath, require, false)
	if err != nil {
		return err
	}

root:
	for _, route := range app.APIBuilder.GetRoutes() {
		if ignoreRoutes != nil {
			for _, pattern := range ignoreRoutes {
				found, _ := regexp.MatchString(pattern, route.Path)
				if found {
					continue root
				}
			}
		}

		sourceFileName := route.SourceFileName

		lastHandler := route.Handlers[len(route.Handlers)-1]
		handlerName := getFunctionName(lastHandler)

		p := strings.Split(handlerName, "/")
		findMethod := p[len(p)-1]
		findMethod = strings.TrimSuffix(findMethod, compilerClousureSuffix) // app.(*api).testBaseController

		fullReferenceSplitter := strings.Split(findMethod, ".")
		findMethod = fullReferenceSplitter[len(fullReferenceSplitter)-1] // testBaseController

		if sourceFileName == "" || !strings.HasSuffix(sourceFileName, ".go") {
			// Newer Go toolchains return "<autogenerated>" for method value wrappers.
			// Resolve from the handler name and package path instead.
			sourceFileName = resolveSourceFile(route.MainHandlerName, goModName, findMethod)
			if sourceFileName == "" {
				continue
			}
		}

		operationName := fmt.Sprintf("[%s]%s", route.Method, strings.ReplaceAll(route.Path, "/", "-"))
		if operationName == debugOperationMethod {
			fmt.Sprintf("d")
		}

		parseRouterMethod(openapi, sourceFileName, findMethod, route, structsMapping, searchIdentifiers, goModName)
	}

	return nil
}